resources:
- ../../base
- ../../extras

images:
  - name: docker.elastic.co/beats/elastic-agent
    newName: docker.elastic.co/beats/elastic-agent
    newTag: 8.2.0-SNAPSHOT

configMapGenerator:
  - name: fleet-configmap-1
    namespace: kube-system
    envs:
      - fleet.config
    literals:
      - FLEET_INSECURE=true
    behavior: merge