apiVersion: batch/v1
kind: CronJob
metadata:
  name: curltrace-elastic.co
spec:
  schedule: "* * * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curltrace-elastic-co
              image: graph/curltrace
              imagePullPolicy: IfNotPresent
              command: ["curltrace", "http://elastic.co"]
              env: []
          restartPolicy: OnFailure
